apiVersion: v2
name: customer-api
description: A Helm chart for deploying the customer API application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    version: 11.0.0
