apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "customer-api.fullname" . }}
  labels:
    app: {{ include "customer-api.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "customer-api.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "customer-api.fullname" . }}
    spec:
      containers:
        - name: customer-api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DATABASE_URL
              value: "mysql://{{ .Values.global.mysql.mysqlUser }}:{{ .Values.global.mysql.mysqlPassword }}@{{ include "customer-api.fullname" . }}-mysql:3306/{{ .Values.global.mysql.mysqlDatabase }}"
